config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include("posts.urls")),
    path('pages/', include("pages.urls")),
]

pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView


urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
]

posts/urls.py
from django.urls import path
from posts import views

urlpatterns = [
    path("", views.PostListView.as_view(), name="list"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("new/", views.PostCreateView.as_view(), name="new"),
]

pages/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.urls import reverse

class Post(models.Model):
    title = models.CharField(max_length=128)
    subtitle = models.CharField(max_length=256)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("detail", args=[self.id])

pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "pages/home.html"

class AboutPageView(TemplateView):
    template_name = "pages/about.html"

    

posts/views.py
from django.views.generic import(
    CreateView,
    ListView,
    DetailView,
)

from .models import Post

class PostListView(ListView):
    template_name = "posts/list.html"
    model = Post

class PostDetailView(DetailView):
    template_name = "posts/detail.html"
    model = Post

class PostCreateView(CreateView):
    template_name = "posts/new.html"
    model = Post
    fields = ["title", "subtitle", "body"]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock title %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">My App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" href="{% url 'home' %}">Home</a>
          <a class="nav-link" href="{% url 'about' %}">About</a>
          <a class="nav-link" href="{% url 'list' %}">Post</a>
          <a class="nav-link" href="{% url 'new' %}">New Post</a>
        </div>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock content %}
  </div>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</body>

</html>

templates/pages/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{% endblock title %}

{% block content %}
<div class="container card" style="width: 18rem; justify-content: center;">
    <img src="{% static 'img/1.png' %}" class="card-img-top p-4" alt="...">
    <div class="card-body">
        <h1>About me</h1>
        <h3>Lizbeth Ramirez</h3>    
    </div>
  </div>
{% endblock content %}

templates/pages/home.html
{% extends 'base.html' %}


{% block title %}{% endblock title %}

{% block content %}
<div class="container">
    <h1>Home</h1>
    <p>Welcome to my home page!</p>
</div>

{% endblock content %}

templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}{{ post.title }}{% endblock title %}

{% block content %}
<h1>{{ post.title }}</h1>
<h3>{{ post.subtitle }}</h3>
<small>Created on: {{ post.created_on }}</small>
<p>{{ post.body }}</p>
{% endblock content %}

templates/posts/list.html
{% extends 'base.html' %}

{% block title %}Posts{% endblock title %}

{% block content %}
<h1>Posts</h1>
{% for post in post_list %}
<div class="card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">{{ post.title }}</h5>
        <h6 class="card-subtitle mb-2 text-body-secondary">{{ post.subtitle }}</h6>
        <p class="card-text">{{ post.body|truncatechars:64 }}</p>
        <a href="{% url 'detail' post.id %}" class="card-link">Continue reading...</a>
    </div>
</div>
<br />
{% endfor %}
{% endblock content %}

templates/posts/new.html
{% extends 'base.html' %}

{% block title %}New Post{% endblock title %}

{% block content %}
<h1>New Post</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="Create">
</form>
{% endblock content %}